const mongoose = require('mongoose');

const jobPostSchema = new mongoose.Schema({
    client: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    title: {
        type: String,
        required: true,
    },
    description: {
        type: String,
        required: true,
    },
    budget: {
        type: Number,
        required: true,
    },
    duration: {
        type: Number,
        required: true,
    },
    skillsRequired: {
        type: [String],
        required: true,
        enum: [
            'HTML',
            'CSS',
            'JavaScript',
            'React',
            'Node.js',
            'MongoDB',
            'Express',
            'Python',
            'Django',
            'Flask',
            'Java',
            'Spring',
            'Android',
            'iOS',
            'Swift',
            'Kotlin',
            'Flutter',
            'Dart',
            'C#',
            'ASP.NET',
            'SQL',
            'C++',
            'C',
            'PHP',
            'Laravel',
            'CodeIgniter',
            'Ruby',
            'Ruby on Rails',
            'Angular',
            'Vue.js',
            'Svelte',
            'UI/UX',
            'Figma',
            'Adobe XD',
            'Sketch',
            'Photoshop',
            'Illustrator',
            'SEO',
            'Digital Marketing',
            'Content Writing',
            'Video Editing',
        ],
    },
    category: {
        type: String,
        required: true,
        enum: [
            'Web Development',
            'Mobile Development',
            'Graphic Design',
            'Digital Marketing',
            'Content Writing',
            'Video Editing',
            'UI/UX Design',
            'SEO',
            'Others',
        ],
    },
    status: {
        type: String,
        enum: ['open', 'in-progress', 'completed'],
        default: 'open',
    },
    createdAt: {
        type: Date,
        default: Date.now,
    },
});

module.exports = mongoose.model('JobPost', jobPostSchema);
